export type Feature = {
  name: string;
  label: string;
  group: string;
  type: 'numeric' | 'categorical' | 'boolean' | 'identifier';
  defaultValue: string | number | boolean;
  options?: readonly string[];
  placeholder?: string;
};

export const FEATURES: Feature[] = [
  {
    name: 'partner_id',
    label: 'Partner ID',
    group: 'Identifier',
    type: 'identifier',
    defaultValue: `partner_${Math.floor(1000 + Math.random() * 9000)}`,
    placeholder: 'e.g., partner_1234',
  },
  {
    name: 'age',
    label: 'Age',
    group: 'Personal Details',
    type: 'numeric',
    defaultValue: 32,
    placeholder: 'e.g., 32',
  },
  {
    name: 'gender',
    label: 'Gender',
    group: 'Personal Details',
    type: 'categorical',
    defaultValue: 'Male',
    options: ['Male', 'Female', 'Other'],
  },
  {
    name: 'location',
    label: 'Location',
    group: 'Personal Details',
    type: 'categorical',
    defaultValue: 'CityA',
    options: ['CityA', 'CityB', 'CityC', 'CityD', 'CityE'],
  },
  {
    name: 'education_level',
    label: 'Education Level',
    group: 'Personal Details',
    type: 'categorical',
    defaultValue: 'Bachelor',
    options: ['High School', 'Diploma', 'Bachelor', 'Master', 'PhD'],
  },
  {
    name: 'marital_status',
    label: 'Marital Status',
    group: 'Personal Details',
    type: 'categorical',
    defaultValue: 'Single',
    options: ['Single', 'Married', 'Divorced', 'Widowed'],
  },
  {
    name: 'dependents',
    label: 'Dependents',
    group: 'Personal Details',
    type: 'numeric',
    defaultValue: 0,
    placeholder: 'e.g., 2',
  },
  {
    name: 'partner_type',
    label: 'Partner Type',
    group: 'Partner Profile',
    type: 'categorical',
    defaultValue: 'Driver',
    options: ['Driver', 'Merchant', 'Agent'],
  },
  {
    name: 'months_with_platform',
    label: 'Months with Platform',
    group: 'Partner Profile',
    type: 'numeric',
    defaultValue: 24,
    placeholder: 'e.g., 24',
  },
  {
    name: 'days_active',
    label: 'Days Active',
    group: 'Partner Profile',
    type: 'numeric',
    defaultValue: 680,
    placeholder: 'e.g., 680',
  },
  {
    name: 'vehicle_age',
    label: 'Vehicle Age (Years)',
    group: 'Partner Profile',
    type: 'numeric',
    defaultValue: 4,
    placeholder: 'e.g., 4',
  },
  {
    name: 'vehicle_maintenance_score',
    label: 'Vehicle Maintenance Score',
    group: 'Partner Profile',
    type: 'numeric',
    defaultValue: 0.82,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'total_trips',
    label: 'Total Trips',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 1200,
    placeholder: 'e.g., 1200',
  },
  {
    name: 'total_orders',
    label: 'Total Orders',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 0,
    placeholder: 'e.g., 300',
  },
  {
    name: 'avg_rating',
    label: 'Average Rating',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 4.8,
    placeholder: '1.0 to 5.0',
  },
  {
    name: 'avg_speed',
    label: 'Average Speed (km/h)',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 35.2,
    placeholder: 'e.g., 35.2',
  },
  {
    name: 'hard_braking_incidents',
    label: 'Hard Braking Incidents',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 3,
    placeholder: 'e.g., 3',
  },
  {
    name: 'late_arrivals',
    label: 'Late Arrivals',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 1,
    placeholder: 'e.g., 1',
  },
  {
    name: 'cancellation_rate',
    label: 'Cancellation Rate',
    group: 'Trip & Order History',
    type: 'numeric',
    defaultValue: 0.04,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'base_monthly_income',
    label: 'Base Monthly Income',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 800,
    placeholder: 'e.g., 800',
  },
  {
    name: 'monthly_earnings',
    label: 'Monthly Earnings',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 950,
    placeholder: 'e.g., 950',
  },
  {
    name: 'income_volatility',
    label: 'Income Volatility',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0.2,
    placeholder: 'e.g., 0.2',
  },
  {
    name: 'earnings_std',
    label: 'Earnings Std. Deviation',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 150.5,
    placeholder: 'e.g., 150.5',
  },
  {
    name: 'earnings_cv',
    label: 'Earnings Coeff. of Variation',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0.18,
    placeholder: 'e.g., 0.18',
  },
  {
    name: 'avg_order_value',
    label: 'Average Order Value',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0,
    placeholder: 'e.g., 15.50',
  },
  {
    name: 'on_time_payments',
    label: 'On-Time Payments',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 24,
    placeholder: 'e.g., 24',
  },
  {
    name: 'payment_delay_days',
    label: 'Payment Delay (Days)',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 1,
    placeholder: 'e.g., 1',
  },
  {
    name: 'savings_rate',
    label: 'Savings Rate',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0.1,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'has_credit',
    label: 'Has Credit History',
    group: 'Financials',
    type: 'boolean',
    defaultValue: true,
  },
  {
    name: 'credit_utilization',
    label: 'Credit Utilization',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0.3,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'credit_score',
    label: 'External Credit Score',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 710,
    placeholder: 'e.g., 710',
  },
  {
    name: 'income_to_volatility_ratio',
    label: 'Income to Volatility Ratio',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 4.75,
    placeholder: 'e.g., 4.75',
  },
  {
    name: 'financial_stability_score',
    label: 'Financial Stability Score',
    group: 'Financials',
    type: 'numeric',
    defaultValue: 0.72,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'avg_session_duration',
    label: 'Avg. Session Duration (min)',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 42.5,
    placeholder: 'e.g., 42.5',
  },
  {
    name: 'avg_response_time',
    label: 'Avg. Response Time (min)',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 3.2,
    placeholder: 'e.g., 3.2',
  },
  {
    name: 'peak_hours_utilization',
    label: 'Peak Hours Utilization',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 0.67,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'support_tickets',
    label: 'Support Tickets',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 2,
    placeholder: 'e.g., 2',
  },
  {
    name: 'resolution_time',
    label: 'Avg. Resolution Time (hrs)',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 12.5,
    placeholder: 'e.g., 12.5',
  },
  {
    name: 'referral_count',
    label: 'Referral Count',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 3,
    placeholder: 'e.g., 3',
  },
  {
    name: 'app_opens_per_day',
    label: 'App Opens per Day',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 5.1,
    placeholder: 'e.g., 5.1',
  },
  {
    name: 'notification_response_rate',
    label: 'Notification Response Rate',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 0.3,
    placeholder: '0.0 to 1.0',
  },
  {
    name: 'platform_efficiency',
    label: 'Platform Efficiency',
    group: 'Platform Engagement',
    type: 'numeric',
    defaultValue: 0.6,
    placeholder: '0.0 to 1.0',
  },
];

export const featureGroups = [
  'Personal Details',
  'Partner Profile',
  'Financials',
  'Trip & Order History',
  'Platform Engagement',
];

export const CSV_TEMPLATE_HEADERS = FEATURES.map(f => f.name).join(',');
