// A great deal of this file was generated by AI.
'use client';

import { useState } from 'react';
import {
  ArrowLeft,
  ArrowRight,
  ShieldCheck,
  Zap,
  BrainCircuit,
  Database,
  Users,
  BarChart,
  Lightbulb,
  GitBranch,
  Target,
  Layers,
  ChevronRight,
  Home,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import Link from 'next/link';
import { cn } from '@/lib/utils';

const FlowchartNode = ({
  label,
  icon: Icon,
  className,
}: {
  label: string;
  icon?: React.ElementType;
  className?: string;
}) => (
  <div
    className={cn(
      'flex flex-col items-center justify-center bg-background border border-border rounded-lg p-4 text-center shadow-md',
      className
    )}
  >
    {Icon && <Icon className="h-8 w-8 mb-2 text-primary" />}
    <p className="text-sm font-medium text-foreground">{label}</p>
  </div>
);

const Arrow = ({ right = false, down = false, className = '' }) => (
  <div
    className={cn(
      'flex items-center justify-center text-muted-foreground',
      className
    )}
  >
    {down ? (
      <ArrowRight className="h-8 w-8 rotate-90" />
    ) : (
      <ArrowRight className="h-8 w-8" />
    )}
  </div>
);

const slides = [
  {
    title: 'Credit ClearView',
    subtitle: 'AI-Powered Credit Risk Assessment for the Gig Economy',
    content: (
      <div className="flex flex-col items-center justify-center text-center">
        <ShieldCheck className="h-24 w-24 text-primary mb-6" />
        <p className="text-xl text-muted-foreground">
          A modern solution for evaluating the financial health of
          non-traditional earners.
        </p>
        <p className="mt-8 text-lg font-semibold">Team: Firebase Studio</p>
      </div>
    ),
  },
  {
    title: 'The Challenge: A Credit Blind Spot',
    content: (
      <div className="grid md:grid-cols-2 gap-8 items-center">
        <div className="space-y-4">
          <h3 className="text-2xl font-semibold text-primary">The Problem</h3>
          <p className="text-muted-foreground">
            Traditional credit scoring models rely on stable, long-term credit
            history and predictable income—luxuries many gig economy workers
            don't have.
          </p>
          <ul className="list-disc list-inside space-y-2 text-left">
            <li>Income is often volatile and project-based.</li>
            <li>No standard salary slips or employment letters.</li>
            <li>This creates a significant credit gap, locking them out of fair financial products.</li>
          </ul>
        </div>
        <div className="flex justify-center">
            <Users className="h-40 w-40 text-destructive opacity-30" />
        </div>
      </div>
    ),
  },
  {
    title: 'Our Solution: A Holistic Approach',
    content: (
      <div className="space-y-6">
        <p className="text-center text-lg text-muted-foreground">
          Credit ClearView leverages alternative data from the platforms they already use to build a more accurate and equitable financial identity.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
            <Card className="p-4">
                <Zap className="mx-auto h-10 w-10 text-accent mb-2"/>
                <h4 className="font-semibold text-lg">Real-Time Data</h4>
                <p className="text-sm text-muted-foreground">Analyzes live operational data, not just past credit history.</p>
            </Card>
            <Card className="p-4">
                <BrainCircuit className="mx-auto h-10 w-10 text-accent mb-2"/>
                <h4 className="font-semibold text-lg">Intelligent Prediction</h4>
                <p className="text-sm text-muted-foreground">Uses a simulated Deep Neural Network for nuanced risk assessment.</p>
            </Card>
            <Card className="p-4">
                <Lightbulb className="mx-auto h-10 w-10 text-accent mb-2"/>
                <h4 className="font-semibold text-lg">Explainable AI (XAI)</h4>
                <p className="text-sm text-muted-foreground">Provides clear reasons for each prediction, building trust.</p>
            </Card>
        </div>
      </div>
    ),
  },
  {
    title: 'System Architecture Flowchart',
    content: (
      <div className="space-y-4">
        <h3 className="text-center font-semibold text-lg">From User Input to AI Insight</h3>
         <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-center">
            <FlowchartNode label="User Input Form (Next.js Frontend)" icon={Users} />
            <Arrow />
            <FlowchartNode label="Server Action Triggered" icon={Zap} />
            <Arrow />
            <FlowchartNode label="Genkit AI Flow" icon={BrainCircuit} />
        </div>
        <div className="flex justify-center">
            <Arrow down={true} className="my-2" />
        </div>
         <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-center">
            <FlowchartNode label="AI Explanation Returned" icon={Lightbulb} className="md:col-start-5"/>
            <Arrow right={true} />
            <FlowchartNode label="Prediction Returned to UI" icon={BarChart} />
            <Arrow right={true} />
            <FlowchartNode label="Call to Google's Gemini Model" icon={Database} />
        </div>
      </div>
    ),
  },
   {
    title: 'Technology Stack',
    content: (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
                <CardContent className="p-6">
                    <h3 className="text-lg font-bold text-primary mb-2">Frontend</h3>
                    <ul className="space-y-1 text-sm text-muted-foreground">
                        <li>Next.js & React</li>
                        <li>TypeScript</li>
                        <li>Tailwind CSS</li>
                        <li>Shadcn/UI</li>
                    </ul>
                </CardContent>
            </Card>
            <Card>
                <CardContent className="p-6">
                    <h3 className="text-lg font-bold text-primary mb-2">AI & Backend</h3>
                    <ul className="space-y-1 text-sm text-muted-foreground">
                        <li>Google's Gemini Model</li>
                        <li>Genkit AI Framework</li>
                        <li>Next.js Server Actions</li>
                    </ul>
                </CardContent>
            </Card>
            <Card>
                <CardContent className="p-6">
                    <h3 className="text-lg font-bold text-primary mb-2">Infrastructure</h3>
                    <ul className="space-y-1 text-sm text-muted-foreground">
                        <li>Firebase App Hosting</li>
                        <li>Node.js Runtime</li>
                        <li>GitHub (for VCS)</li>
                    </ul>
                </CardContent>
            </Card>
        </div>
    )
  },
  {
    title: 'Key Features & Implementation',
    content: (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
                <div className="flex items-start gap-4">
                    <Layers className="h-6 w-6 text-primary mt-1 shrink-0"/>
                    <div>
                        <h4 className="font-semibold">Dual Prediction Modes</h4>
                        <p className="text-sm text-muted-foreground">Supports both single, on-demand predictions and bulk processing via CSV upload for scalability.</p>
                    </div>
                </div>
                 <div className="flex items-start gap-4">
                    <BarChart className="h-6 w-6 text-primary mt-1 shrink-0"/>
                    <div>
                        <h4 className="font-semibold">Interactive Results</h4>
                        <p className="text-sm text-muted-foreground">Visualizes prediction probabilities with dynamic charts and provides detailed AI-powered explanations.</p>
                    </div>
                </div>
            </div>
             <div className="space-y-4">
                <div className="flex items-start gap-4">
                    <GitBranch className="h-6 w-6 text-primary mt-1 shrink-0"/>
                    <div>
                        <h4 className="font-semibold">Modular AI Flows</h4>
                        <p className="text-sm text-muted-foreground">Genkit flows for prediction, explanation, and feature-details are separated for maintainability and clarity.</p>
                    </div>
                </div>
                 <div className="flex items-start gap-4">
                    <Zap className="h-6 w-6 text-primary mt-1 shrink-0"/>
                    <div>
                        <h4 className="font-semibold">"Generate Random Data"</h4>
                        <p className="text-sm text-muted-foreground">A utility feature that simplifies testing and demonstration of the prediction engine.</p>
                    </div>
                </div>
            </div>
        </div>
    ),
  },
  {
    title: 'Future Roadmap',
    content: (
        <div className="space-y-6">
             <p className="text-center text-lg text-muted-foreground">
              Building on our robust foundation, we plan to enhance the platform's capabilities.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
                <div className="flex items-center gap-4">
                    <Target className="h-8 w-8 text-accent"/>
                    <p className="font-medium">Transition to a true, fine-tuned ML model.</p>
                </div>
                 <div className="flex items-center gap-4">
                    <Target className="h-8 w-8 text-accent"/>
                    <p className="font-medium">Develop a partner-facing dashboard.</p>
                </div>
                 <div className="flex items-center gap-4">
                    <Target className="h-8 w-8 text-accent"/>
                    <p className="font-medium">Build a REST API for third-party integration.</p>
                </div>
                 <div className="flex items-center gap-4">
                    <Target className="h-8 w-8 text-accent"/>
                    <p className="font-medium">Implement historical trend analysis.</p>
                </div>
            </div>
        </div>
    )
  },
  {
    title: 'Thank You',
    content: (
      <div className="flex flex-col items-center justify-center text-center">
        <h3 className="text-3xl font-bold mb-4">Q & A</h3>
        <p className="text-xl text-muted-foreground">
            Ready to redefine credit scoring for the modern workforce.
        </p>
      </div>
    ),
  },
];


export default function PresentationPage() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev < slides.length - 1 ? prev + 1 : prev));
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev > 0 ? prev - 1 : prev));
  };

  const slide = slides[currentSlide];

  return (
    <div className="flex flex-col min-h-screen bg-gray-900 text-gray-100 p-4 font-body">
        <header className="flex justify-between items-center mb-4">
            <div className="flex items-center gap-2">
                <ShieldCheck className="h-7 w-7 text-primary" />
                <h1 className="text-xl font-semibold font-headline tracking-tight text-white">
                Credit ClearView Presentation
                </h1>
            </div>
             <Button asChild variant="outline">
                <Link href="/">
                    <Home className="mr-2" /> Back to App
                </Link>
            </Button>
        </header>

      <div className="flex-1 flex flex-col items-center justify-center">
        <div className="w-full max-w-5xl bg-gray-800 border border-gray-700 rounded-xl shadow-2xl p-8 md:p-12 transition-all duration-300">
            <div className="mb-6 min-h-[4rem]">
                <h2 className="text-4xl font-bold font-headline text-white">{slide.title}</h2>
                {slide.subtitle && <p className="text-lg text-primary mt-2">{slide.subtitle}</p>}
            </div>
            <div className="min-h-[20rem] flex items-center">
                <div className="w-full">
                    {slide.content}
                </div>
            </div>
        </div>
      </div>

      <footer className="mt-auto pt-4">
        <div className="flex justify-between items-center max-w-5xl mx-auto">
          <Button onClick={prevSlide} disabled={currentSlide === 0} variant="secondary">
            <ArrowLeft className="mr-2" /> Previous
          </Button>
          <div className="text-sm text-gray-400">
            Slide {currentSlide + 1} of {slides.length}
          </div>
          <Button onClick={nextSlide} disabled={currentSlide === slides.length - 1} variant="secondary">
            Next <ArrowRight className="ml-2" />
          </Button>
        </div>
      </footer>
    </div>
  );
}
